### ISSUE TITLE
Add maintainers

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/silx-feedstock#2]
@conda-forge/pyfai any takers?

**Comment by CJ-Wright** [comment]
@tschoonj would you like to be a maintainer?

**Comment by tschoonj** [comment]
I am not really associated with this project, just an occasional user.

If that's good enough for you, then go ahead and add me 😄

**Comment by CJ-Wright** [comment]
I'm closing this, if anyone wants in just let me know by commenting in this issue or opening a new one.
