### ISSUE TITLE
New maintainers?

### ISSUE THREAD

**Issue by vallsv** [conda-forge/silx-feedstock#25]
Hi,

I am part of the team developing silx, fabio, pyFAI.
As i am now using conda in our company, it would be very helpful to became maintainer, if you like.

You also can include @t20100, who is the silx architect.

Regards,

**Comment by CJ-Wright** [comment]
Can you please open a PR adding yourself?
https://github.com/conda-forge/silx-feedstock/blob/master/recipe/meta.yaml#L68

**Comment by vallsv** [comment]
Yes sure.
Here is a PR #26

**Comment by vallsv** [comment]
Thanks a lot
